---
name: Examples

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  codeblocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Cache pooch
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ~/.cache/sleplet
          key: readme-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e '.[readme]'

      - name: Run examples in the README
        run: python -m pytest --codeblocks .github README.md documentation

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Cache pooch
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ~/.cache/sleplet
          key: examples-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e .[docs]

      - name: Run examples in the examples folder
        run: >-
          find examples -name "*.py" -exec sh -c 'for f; do printf "\n$f\n";
          python "$f" || exit 1; done' sh {} +
