---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@a572508d17fc531e8ad9c0389c0fe51d522b2204 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          licence-file: ./LICENCE.txt
